// <auto-generated />
using System;
using Bespereboiniki.Datalayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bespereboiniki.Datalayer.Migrations
{
    [DbContext(typeof(UPSContext))]
    [Migration("20210505132238_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Bespereboiniki.Datalayer.Tables.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29f65e7-43b9-4a14-9ab2-ddca2312f2e3"),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("57eb14fb-cfb9-43b6-869d-28bb06e57540"),
                            Name = "manager"
                        });
                });

            modelBuilder.Entity("Bespereboiniki.Datalayer.Tables.UPS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uin")
                        .HasColumnType("int");

                    b.Property<int>("Uout")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UPSes");
                });

            modelBuilder.Entity("Bespereboiniki.Datalayer.Tables.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("869ab7ac-227d-4f45-b6b7-30455bd86a83"),
                            FirstName = "Админ",
                            LastName = "Фсея Руси",
                            Login = "admin",
                            Password = "admin",
                            RoleId = new Guid("b29f65e7-43b9-4a14-9ab2-ddca2312f2e3"),
                            Surname = "Админович"
                        },
                        new
                        {
                            Id = new Guid("1af8d4a8-0577-4f7b-a917-2083cf3590d7"),
                            FirstName = "Менеджер",
                            LastName = "Фсея Бесперебойники.рф",
                            Login = "manager",
                            Password = "manager",
                            RoleId = new Guid("57eb14fb-cfb9-43b6-869d-28bb06e57540"),
                            Surname = "Менеджерович"
                        });
                });

            modelBuilder.Entity("Bespereboiniki.Datalayer.Tables.User", b =>
                {
                    b.HasOne("Bespereboiniki.Datalayer.Tables.Role", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
